options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: asia-southeast1-docker.pkg.dev/heymax-kelvin-analytics/dbt-images/dbt-runner:prod
    id: Build dbt tables
    dir: dbt/heymax_dbt_data_tables
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p /builder/home/.dbt
        cat > /builder/home/.dbt/profiles.yml <<EOF
        heymax_dbt_data_tables:
          target: dev
          outputs:
            dev:
              type: bigquery
              method: oauth
              project: heymax-kelvin-analytics
              schema: base
              location: asia-southeast1
              threads: 4
        EOF
        dbt deps
        dbt run --profiles-dir /builder/home/.dbt

timeout: 900s
