name: 'heymax_dbt_data_tables'
version: '1.0.0'

profile: 'heymax_dbt_data_tables'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  heymax_dbt_data_tables:
    staging:
      +materialized: table
      +dataset: heymax_staging
    marts/core_tables:
      +materialized: table
      +dataset: heymax_core
    marts/analytics_tables:
      +materialized: view
      +dataset: heymax_analytics
        
