executor: KubernetesExecutor
airflowVersion: "2.10.5"

dags:
  mountPath: /opt/airflow/dags
  gitSync:
    enabled: true
    repo: "https://github.com/kelvinlimwj/kelvin-heymax-analytics-pipeline.git"
    branch: "main"
    subPath: "airflow_dags"
    depth: 1
    period: 5s
    containerName: git-sync
    uid: 65533

gcpServiceAccount: airflow-kubernetes@heymax-kelvin-analytics.iam.gserviceaccount.com

serviceAccount:
  create: false
  name: airflow-kubernetes

scheduler:
  serviceAccount:
    name: airflow-scheduler
    annotations:
      iam.gke.io/gcp-service-account: airflow-kubernetes@heymax-kelvin-analytics.iam.gserviceaccount.com
  env:
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo/airflow_dags

webserver:
  serviceAccount:
    name: airflow-webserver
    annotations:
      iam.gke.io/gcp-service-account: airflow-kubernetes@heymax-kelvin-analytics.iam.gserviceaccount.com
  env:
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo/airflow_dags

workers:
  serviceAccount:
    name: airflow-worker
    annotations:
      iam.gke.io/gcp-service-account: airflow-kubernetes@heymax-kelvin-analytics.iam.gserviceaccount.com
  env:
    - name: AIRFLOW__CORE__REMOTE_LOGGING
      value: "True"
    - name: AIRFLOW__CORE__REMOTE_LOG_CONN_ID
      value: "google_cloud_default"
    - name: AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER
      value: "gs://heymax_kelvin_airflow_logs"
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo/airflow_dags

triggerer:
  serviceAccount:
    name: airflow-triggerer
    annotations:
      iam.gke.io/gcp-service-account: airflow-kubernetes@heymax-kelvin-analytics.iam.gserviceaccount.com

config:
  core:
    dags_folder: /opt/airflow/dags/repo/airflow_dags
    executor: KubernetesExecutor
    load_examples: 'False'
    remote_logging: "True"
    remote_log_conn_id: "google_cloud_default"
    remote_base_log_folder: "gs://heymax_kelvin_airflow_logs"
    auth_manager: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"

  kubernetes:
    delete_worker_pods: "False"

  logging:
    remote_logging: "True"
    remote_log_conn_id: "google_cloud_default"
    remote_base_log_folder: "gs://heymax_kelvin_airflow_logs"

  webserver:
    enable_proxy_fix: 'True'

connections:
  - id: google_cloud_default
    type: google_cloud_platform
    extra: '{"extra__google_cloud_platform__project":"heymax-kelvin-analytics"}'
