steps:
  - name: asia-southeast1-docker.pkg.dev/heymax-kelvin-analytics/dbt-images/dbt-runner:latest
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p /builder/home/.dbt
        cat > /builder/home/.dbt/profiles.yml <<EOF
        dbt_bigquery_analytics:
          target: dev
          outputs:
            dev:
              type: bigquery
              method: oauth
              project: heymax-kelvin-analytics
              dataset: heymax_analytics
              location: US
              threads: 4
        EOF
        dbt deps
        dbt run --profiles-dir /builder/home/.dbt

timeout: 900s
